[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cooking_bot"
version = "0.1.0"
readme = "README.md"

[project.scripts]
cooking-bot = "cooking_bot.conversation:main"